name: Generate Pac-Man Game

on:
  schedule:
    # Roda automaticamente a cada 24 horas (ajuste o cron se preferir)
    - cron: "0 */24 * * *"
  workflow_dispatch: # Permite que você execute manualmente quando quiser
  push:
    branches:
      - main # Roda em push para a branch principal

jobs:
  generate:
    permissions:
      contents: write # Permissão para a Action escrever o arquivo SVG
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
